### PR TITLE
Modify the validity check regex to allow 'element.class.class'

### PR DESCRIPTION
**Pull request by watzon**

### CODE REVIEW

**Comment by iDev0urer** [comment]
Fixes #301

**Comment by SimenB** [comment]
@iDev0urer Thanks for the PRs! Stuff is supposed to be merged into the `develop` branch,  which is then merged into `master` whenever Ross cuts a new release.
Maybe we should do away with that though, I don't really see the benefit (in this sort of projects, I've used git-flow at work before 😄). @rossPatton, thoughts?

**Comment by iDev0urer** [comment]
Yeah I like the idea of git flow. Gives a sense of organization. If @rossPatton wants I can redo all of my pulls to point to the dev branch instead. And I'll go see about adding tests

**Comment by SimenB** [comment]
I dropped the develop branch. Just add a test or two, and this should be GTG

**Pull request closed without merging**
